"""Constants for the ZTE Router integration."""

DOMAIN = "zte_router"
DEFAULT_USERNAME = "admin"
DEVICE_NAME = "ZTE MC Series"
MANUFACTURER = "ZTE"
MODEL = "MC Series"
ROUTER_TYPE_MC801 = "MC801"
ROUTER_TYPE_MC888 = "MC888"
ROUTER_TYPE_MC889 = "MC889"
ROUTER_TYPE_G5_ULTRA = "G5 Ultra"
SUPPORTED_ROUTER_TYPES = [
    ROUTER_TYPE_MC801,
    ROUTER_TYPE_MC888,
    ROUTER_TYPE_MC889,
    ROUTER_TYPE_G5_ULTRA,
]
DEFAULT_ALLOW_STALE_DATA = True
CONF_ALLOW_STALE_DATA = "allow_stale_data"


# Define friendly names for the sensors
SENSOR_NAMES = {
    "wa_inner_version": "Firmware Version",
    "cr_version": "CR Version",
    "network_type": "Network Type",
    "rssi": "RSSI",
    "rscp": "RSCP",
    "rmcc": "RMCC",
    "rmnc": "RMNC",
    "enodeb_id": "eNodeB ID",
    "lte_rsrq": "LTE RSRQ",
    "lte_rsrp": "LTE RSRP",
    "Z5g_rsrp": "5G RSRP",
    "ZCELLINFO_band": "Cell Info Band",
    "Z5g_dlEarfcn": "5G DL EARFCN",
    "lte_ca_pcell_arfcn": "LTE CA PCell ARFCN",
    "lte_ca_pcell_band": "LTE CA PCell Band",
    "lte_ca_scell_band": "LTE CA SCell Band",
    "lte_ca_pcell_bandwidth": "LTE CA PCell Bandwidth",
    "lte_ca_scell_info": "LTE CA SCell Info",
    "lte_ca_scell_bandwidth": "LTE CA SCell Bandwidth",
    "wan_lte_ca": "WAN LTE CA",
    "lte_pci": "LTE PCI",
    "Z5g_CELL_ID": "5G Cell ID",
    "Z5g_SINR": "5G SINR",
    "Z5g_snr": "5G SNR",
    "cell_id": "Cell ID",
    "wan_active_band": "WAN Active Band",
    "nr5g_pci": "NR 5G PCI",
    "nr5g_action_band": "NR 5G Action Band",
    "nr5g_cell_id": "NR 5G Cell ID",
    "lte_snr": "LTE SNR",
    "ecio": "EC/IO",
    "wan_active_channel": "WAN Active Channel",
    "nr5g_action_channel": "NR 5G Action Channel",
    "ngbr_cell_info": "Neighbor Cell Info",
    "monthly_tx_bytes": "Monthly TX Bytes",
    "monthly_rx_bytes": "Monthly RX Bytes",
    "wan_ipaddr": "WAN IP Address",
    "wan_apn": "WAN APN",
    "pm_sensor_mdm": "PM Sensor MDM",
    "pm_modem_5g": "PM Modem 5G",
    "dns_mode": "DNS Mode",
    "prefer_dns_manual": "Preferred DNS Manual",
    "standby_dns_manual": "Standby DNS Manual",
    "static_wan_ipaddr": "Static WAN IP Address",
    "opms_wan_mode": "OPMS WAN Mode",
    "opms_wan_auto_mode": "OPMS WAN Auto Mode",
    "loginfo": "Log Info",
    "realtime_time": "Realtime Time",
    "signalbar": "Signal Bar",
    "modem_main_state": "Modem Main State",
    "pin_status": "PIN Status",
    "new_version_state": "New Version State",
    "current_upgrade_state": "Current Upgrade State",
    "is_mandatory": "Is Mandatory",
    "wifi_dfs_status": "WiFi DFS Status",
    "battery_value": "Battery Value",
    "ppp_dial_conn_fail_counter": "PPP Dial Conn Fail Counter",
    "wifi_chip1_ssid1_auth_mode": "WiFi Chip1 SSID1 Auth Mode",
    "wifi_chip2_ssid1_auth_mode": "WiFi Chip2 SSID1 Auth Mode",
    "network_provider": "Network Provider",
    "simcard_roam": "Simcard Roam",
    "spn_name_data": "SPN Name Data",
    "spn_b1_flag": "SPN B1 Flag",
    "spn_b2_flag": "SPN B2 Flag",
    "wifi_onoff_state": "WiFi On/Off State",
    "wifi_chip1_ssid1_ssid": "WiFi Chip1 SSID1 SSID",
    "wifi_chip2_ssid1_ssid": "WiFi Chip2 SSID1 SSID",
    "pppoe_status": "PPPoE Status",
    "dhcp_wan_status": "DHCP WAN Status",
    "static_wan_status": "Static WAN Status",
    "mdm_mcc": "MDM MCC",
    "mdm_mnc": "MDM MNC",
    "EX_SSID1": "EX SSID1",
    "sta_ip_status": "STA IP Status",
    "EX_wifi_profile": "EX WiFi Profile",
    "m_ssid_enable": "M SSID Enable",
    "RadioOff": "Radio Off",
    "wifi_chip1_ssid1_access_sta_num": "WiFi Chip1 SSID1 Access STA Num",
    "wifi_chip2_ssid1_access_sta_num": "WiFi Chip2 SSID1 Access STA Num",
    "lan_ipaddr": "LAN IP Address",
    "station_mac": "Station MAC",
    "wifi_access_sta_num": "WiFi Access STA Num",
    "battery_charging": "Battery Charging",
    "battery_vol_percent": "Battery Vol Percent",
    "battery_pers": "Battery Percent",
    "realtime_tx_bytes": "Realtime TX Bytes",
    "realtime_rx_bytes": "Realtime RX Bytes",
    "realtime_tx_thrpt": "Realtime TX Throughput",
    "realtime_rx_thrpt": "Realtime RX Throughput",
    "monthly_time": "Monthly Time",
    "date_month": "Date Month",
    "data_volume_limit_switch": "Data Volume Limit Switch",
    "data_volume_limit_size": "Data Volume Limit Size",
    "data_volume_alert_percent": "Data Volume Alert Percent",
    "data_volume_limit_unit": "Data Volume Limit Unit",
    "roam_setting_option": "Roam Setting Option",
    "upg_roam_switch": "Upgrade Roam Switch",
    "ssid": "SSID",
    "wifi_enable": "WiFi Enable",
    "wifi_5g_enable": "WiFi 5G Enable",
    "check_web_conflict": "Check Web Conflict",
    "dial_mode": "Dial Mode",
    "privacy_read_flag": "Privacy Read Flag",
    "is_night_mode": "Is Night Mode",
    "vpn_conn_status": "VPN Connection Status",
    "wan_connect_status": "WAN Connection Status",
    "sms_received_flag": "SMS Received Flag",
    "sts_received_flag": "STS Received Flag",
    "sms_unread_num": "SMS Unread Number",
    "wifi_chip1_ssid2_access_sta_num": "WiFi Chip1 SSID2 Access STA Num",
    "wifi_chip2_ssid2_access_sta_num": "WiFi Chip2 SSID2 Access STA Num",
    "ppp_status": "PPP Status",
    # New SMS related sensors
    "sms_nv_total": "SMS Capacity device",
    "sms_capacity_left": "SMS Capacity left",
    "sms_sim_total": "SMS Capacity SIM",
    "sms_nv_rev_total": "Recieved SMS-s",
    "sms_nv_send_total": "Sent SMS-s",
    "sms_nv_draftbox_total": "SMS NV Draftbox Total",
    "sms_sim_received_total": "SMS SIM Received Total",
    "sms_sim_sent_total": "SMS SIM Sent Total",
    "sms_sim_draftbox_total": "SMS SIM Draftbox Total",
    #Additional Sensors names
    "lte_multi_ca_scell_info": "LTE Multi CA SCell Info",
    "lte_multi_ca_scell_sig_info": "LTE Multi CA SCell Signal Info",
    "nr_ca_pcell_band": "NR CA PCell Band",
    "nr_ca_pcell_freq": "NR CA PCell Frequency",
    "nr_multi_ca_scell_info": "NR Multi CA SCell Info",
    "nr5g_action_nsa_band": "NR 5G NSA Action Band",
    "nr5g_sa_band_lock": "NR 5G SA Band Lock",
    "nr5g_nsa_band_lock": "NR 5G NSA Band Lock",
    "pm_sensor_ambient": "Ambient Sensor Temp",
    "pm_sensor_pa1": "PA Sensor Temp",
    "wifi_chip_temp": "WiFi Chip Temperature",
    "5g_rx0_rsrp": "5G RX0 RSRP",
    "5g_rx1_rsrp": "5G RX1 RSRP",
    "Z5g_rsrq": "5G RSRQ",
    "rscp_1": "RSCP 1",
    "rscp_2": "RSCP 2",
    "rscp_3": "RSCP 3",
    "rscp_4": "RSCP 4",
    "ecio_1": "ECIO 1",
    "ecio_2": "ECIO 2",
    "ecio_3": "ECIO 3",
    "ecio_4": "ECIO 4",
    "lte_rsrp_1": "LTE RSRP 1",
    "lte_rsrp_2": "LTE RSRP 2",
    "lte_rsrp_3": "LTE RSRP 3",
    "lte_rsrp_4": "LTE RSRP 4",
    "lte_snr_1": "LTE SNR 1",
    "lte_snr_2": "LTE SNR 2",
    "lte_snr_3": "LTE SNR 3",
    "lte_snr_4": "LTE SNR 4",
    "apn_interface_version": "APN Interface Version",
    "bandwidth": "Bandwidth",
    "guest_switch": "Guest Switch",
    "imei": "IMEI",
    "ip_passthrough_enabled": "IP Passthrough Enabled",
    "lte_band": "LTE Band",
    "lte_ca_pcell_freq": "LTE CA PCell Frequency",
    "lte_ca_scell_arfcn": "LTE CA SCell ARFCN",
    "lte_earfcn_lock": "LTE EARFCN Lock",
    "lte_pci_lock": "LTE PCI Lock",
    "lte_rssi": "LTE RSSI",
    "m_SSID2": "M SSID2",
    "network_provider_fullname": "Network Provider Fullname",
    "pm_sensor_5g": "PM Sensor 5G",
    "tx_power": "TX Power",
    "wifi_chip1_ssid1_wifi_coverage": "WiFi Chip1 SSID1 Coverage",
    "wifi_chip1_ssid2_max_access_num": "WiFi Chip1 SSID2 Max Access Num",
    "wifi_chip2_ssid2_max_access_num": "WiFi Chip2 SSID2 Max Access Num",
    "flux_realtime_tx_bytes": "FLUX Realtime TX",
    "flux_realtime_rx_bytes": "FLUX Realtime RX",
    "flux_realtime_time": "FLUX Realtime Time",
    "flux_realtime_tx_thrpt": "FLUX Realtime TX Speed",
    "flux_realtime_rx_thrpt": "FLUX Realtime RX Speed",
    "flux_monthly_tx_bytes": "FLUX Monthly TX",
    "flux_monthly_rx_bytes": "FLUX Monthly RX",
    "flux_monthly_time": "FLUX Monthly Time",
    "flux_data_volume_limit_size": "FLUX Data Plan Limit",
    "flux_data_volume_alert_percent": "FLUX Alert Threshold",
    "flux_data_volume_limit_unit": "FLUX Limit Unit",
    "date_month": "FLUX Current Billing Month",
    "LocalDomain": "Local Domain",
    "hardware_version": "Hardware Version",
    "iccid": "SIM ICCID",
    "imsi": "SIM IMSI",
    "sim_imsi": "SIM IMSI (Secondary)",
    "wa_version": "Web App Version",
    "web_version": "Web Version",
    "mac_address": "MAC Address",
    "ipv6_pdp_type": "IPv6 PDP Type",
    "ipv6_pdp_type_ui": "IPv6 PDP Type (UI)",
    "ipv6_wan_ipaddr": "IPv6 WAN IP Address",
    "pdp_type": "PDP Type",
    "pdp_type_ui": "PDP Type (UI)",
    "sms_dev_unread_num": "Device Unread SMS Count",
    "sms_sim_unread_num": "SIM Unread SMS Count",
    "wifi_chip1_ssid1_max_access_num": "WiFi Chip1 SSID1 Max Clients",
    "wifi_chip1_ssid1_password_encode": "WiFi Chip1 SSID1 Password (Encoded)",
    "wifi_chip1_ssid1_switch_onoff": "WiFi Chip1 SSID1 Enabled",
    "wifi_chip1_ssid2_ssid": "WiFi Chip1 SSID2 Name",
    "wifi_chip1_ssid2_switch_onoff": "WiFi Chip1 SSID2 Enabled",
    "wifi_chip2_ssid1_max_access_num": "WiFi Chip2 SSID1 Max Clients",
    "wifi_chip2_ssid1_password_encode": "WiFi Chip2 SSID1 Password (Encoded)",
    "wifi_chip2_ssid1_switch_onoff": "WiFi Chip2 SSID1 Enabled",
    "wifi_chip2_ssid2_ssid": "WiFi Chip2 SSID2 Name",
    "wifi_chip2_ssid2_switch_onoff": "WiFi Chip2 SSID2 Enabled",
    "wifi_lbd_enable": "WiFi LBD (Load Balancing) Enabled",
    "m_HideSSID": "Hidden SSID Mode",
    "station_ip_addr": "Station IP Address",
    "Nr_fcn": "NR Frequency Channel Number",
    "Nr_pci": "NR PCI",
    "Nr_bands": "NR Bands",
    "Nr_band_widths": "NR Bandwidths",
    "Nr_cell_id": "NR Cell ID",
    "Nr_signal_strength": "NR Signal Strength",
    "Nr_snr": "NR SNR",
    "nr_rsrp": "NR RSRP",
    "nr_rsrq": "NR RSRQ",
    "nr_rssi": "NR RSSI",
    "Lte_ca_status": "LTE CA Status",
}

# Define which sensors should be included in the Diagnostics section
DIAGNOSTICS_SENSORS = {
    "sms_capacity_left",
    "last_sms",
    "signalbar",
    "connected_bands",
    # Add other sensors you want to include in Diagnostics
}

# Define units of measurement for the sensors
UNITS = {
    "connection_uptime": "hours",
    "wa_inner_version": None,
    "cr_version": None,
    "network_type": None,
    "rssi": "dBm",
    "rscp": "dBm",
    "rmcc": None,
    "rmnc": None,
    "enodeb_id": None,
    "lte_rsrq": "dB",
    "lte_rsrp": "dBm",
    "Z5g_snr": "dB",
    "Z5g_rsrp": "dBm",
    "ZCELLINFO_band": None,
    "Z5g_dlEarfcn": None,
    "lte_ca_pcell_arfcn": None,
    "lte_ca_pcell_band": None,
    "lte_ca_scell_band": None,
    "lte_ca_pcell_bandwidth": "MHz",
    "lte_ca_scell_info": None,
    "lte_ca_scell_bandwidth": "MHz",
    "wan_lte_ca": None,
    "lte_pci": None,
    "Z5g_CELL_ID": None,
    "Z5g_SINR": "dB",
    "cell_id": None,
    "wan_active_band": None,
    "nr5g_pci": None,
    "nr5g_action_band": None,
    "nr5g_cell_id": None,
    "lte_snr": "dB",
    "ecio": "dB",
    "wan_active_channel": None,
    "nr5g_action_channel": None,
    "ngbr_cell_info": None,
    "monthly_tx_bytes": "B",
    "monthly_rx_bytes": "B",
    "wan_ipaddr": None,
    "wan_apn": None,
    "pm_sensor_mdm": "°C",
    "pm_modem_5g": "°C",
    "dns_mode": None,
    "prefer_dns_manual": None,
    "standby_dns_manual": None,
    "static_wan_ipaddr": None,
    "opms_wan_mode": None,
    "opms_wan_auto_mode": None,
    "ppp_status": None,
    "loginfo": None,
    "realtime_time": "seconds",
    "signalbar": None,
    "modem_main_state": None,
    "pin_status": None,
    "new_version_state": None,
    "current_upgrade_state": None,
    "is_mandatory": None,
    "wifi_dfs_status": None,
    "battery_value": "%",
    "ppp_dial_conn_fail_counter": None,
    "wifi_chip1_ssid1_auth_mode": None,
    "wifi_chip2_ssid1_auth_mode": None,
    "network_provider": None,
    "simcard_roam": None,
    "spn_name_data": None,
    "spn_b1_flag": None,
    "spn_b2_flag": None,
    "wifi_onoff_state": None,
    "wifi_chip1_ssid1_ssid": None,
    "wifi_chip2_ssid1_ssid": None,
    "pppoe_status": None,
    "dhcp_wan_status": None,
    "static_wan_status": None,
    "mdm_mcc": None,
    "mdm_mnc": None,
    "EX_SSID1": None,
    "sta_ip_status": None,
    "EX_wifi_profile": None,
    "m_ssid_enable": None,
    "RadioOff": None,
    "wifi_chip1_ssid1_access_sta_num": None,
    "wifi_chip2_ssid1_access_sta_num": None,
    "lan_ipaddr": None,
    "station_mac": None,
    "wifi_access_sta_num": None,
    "battery_charging": None,
    "battery_vol_percent": "%",
    "battery_pers": "%",
    "realtime_tx_bytes": "bytes",
    "realtime_rx_bytes": "bytes",
    "realtime_tx_thrpt": "bps",
    "realtime_rx_thrpt": "bps",
    "monthly_time": "seconds",
    "date_month": None,
    "data_volume_limit_switch": None,
    "data_volume_limit_size": None,
    "data_volume_alert_percent": "%",
    "data_volume_limit_unit": None,
    "roam_setting_option": None,
    "upg_roam_switch": None,
    "ssid": None,
    "wifi_enable": None,
    "wifi_5g_enable": None,
    "check_web_conflict": None,
    "dial_mode": None,
    "privacy_read_flag": None,
    "is_night_mode": None,
    "vpn_conn_status": None,
    "wan_connect_status": None,
    "sms_received_flag": None,
    "sts_received_flag": None,
    "sms_unread_num": None,
    "wifi_chip1_ssid2_access_sta_num": None,
    "wifi_chip2_ssid2_access_sta_num": None,
    "static_wan_ipaddr": None,
    "dns_mode": None,
    "prefer_dns_manual": None,
    "standby_dns_manual": None,
    "signalbar": None,
    "ppp_status": None,
    "sms_nv_total": None,
    "sms_sim_total": None,
    "sms_nv_received_total": None,
    "sms_nv_sent_total": None,
    "sms_nv_draftbox_total": None,
    "sms_sim_received_total": None,
    "sms_sim_sent_total": None,
    "sms_sim_draftbox_total": None,
    "lte_rsrp_1": "dBm",
    "lte_rsrp_2": "dBm",
    "lte_rsrp_3": "dBm",
    "lte_rsrp_4": "dBm",
    "lte_snr_1": "dB",
    "lte_snr_2": "dB",
    "lte_snr_3": "dB",
    "lte_snr_4": "dB",
    "5g_rx0_rsrp": "dBm",
    "5g_rx1_rsrp": "dBm",
    "Z5g_rsrq": "dB",
    "rscp_1": "dBm",
    "rscp_2": "dBm",
    "rscp_3": "dBm",
    "rscp_4": "dBm",
    "ecio_1": "dB",
    "ecio_2": "dB",
    "ecio_3": "dB",
    "ecio_4": "dB",
    "pm_sensor_ambient": "°C",
    "pm_sensor_pa1": "°C",
    "wifi_chip_temp": "°C",
    "flux_realtime_tx_packets": "packets",
    "flux_realtime_rx_packets": "packets",
    "flux_realtime_tx_drop_packets": "packets",
    "flux_realtime_rx_drop_packets": "packets",
    "flux_realtime_tx_error_packets": "packets",
    "flux_realtime_rx_error_packets": "packets",
    "flux_realtime_max_tx_thrpt": "bps",
    "flux_realtime_max_rx_thrpt": "bps",
    "flux_monthly_tx_packets": "packets",
    "flux_monthly_rx_packets": "packets",
    "flux_monthly_tx_drop_packets": "packets",
    "flux_monthly_rx_drop_packets": "packets",
    "flux_monthly_tx_error_packets": "packets",
    "flux_monthly_rx_error_packets": "packets",
    "flux_total_time": "seconds",
    "flux_total_tx_bytes": "bytes",
    "flux_total_rx_bytes": "bytes",
    "flux_total_tx_packets": "packets",
    "flux_total_rx_packets": "packets",
    "flux_total_tx_drop_packets": "packets",
    "flux_total_rx_drop_packets": "packets",
    "flux_total_tx_error_packets": "packets",
    "flux_total_rx_error_packets": "packets",
    "flux_data_volume_limit_enable": None,
    "flux_data_volume_limit_type": None,
    "flux_data_volume_overflow": None,
    "flux_data_volume_auto_clear_enable": None,
    "flux_data_volume_clearday": None,
}

# Define which sensors should be disabled by default for each router type
DISABLED_SENSORS_MC889 = {
    "concat_sms_received": True,
    "concat_sms_total": True,
    "content": True,
    "cr_version": True,
    "date": True,
    "id": True,
    "is_mandatory": True,
    "is_night_mode": True,
    "lte_ca_scell_arfcn": True,
    "lte_earfcn_lock": True,
    "lte_pci_lock": True,
    "sms_nv_draftbox_total": True,
    "sms_sim_total": True,
    "sms_class": True,
    "sms_dev_unread_num": True,
    "sms_sim_rev_total": True,
    "sms_sim_send_total": True,
    "sms_sim_unread_num": True,
    "sms_nv_received_total":True,
    "sms_received_flag":True,
    "tag": True,
    "wifi_5g_enable": True,
    "wifi_access_sta_num": True,
    "wifi_chip1_ssid1_access_sta_num": True,
    "wifi_chip1_ssid1_auth_mode": True,
    "wifi_chip1_ssid1_ssid": True,
    "wifi_chip1_ssid2_access_sta_num": True,
    "wifi_chip2_ssid1_access_sta_num": True,
    "wifi_chip2_ssid1_auth_mode": True,
    "wifi_chip2_ssid1_auth_mode": True,
    "wifi_chip2_ssid1_ssid": True,
    "wifi_chip2_ssid2_access_sta_num": True,
    "wifi_dfs_status": True,
    "wifi_enable": True,
    "wifi_on_off_state": True,
    "m_ssid_enable": True,
    "ex_wifi_profile": True,
    "ex_ssid1": True,
    "draft_group_id": True,
    #MC889
    "5g_cell_id": True,
    "5g_dl_earfcn": True,
    "cell_info_band": True,
    "data_volume_limit_size": True,
    "ex_ssid1": True,
    "ex_wifi_profile": True,
    "nr_5g_cell_id": True,
    "preferred_dns_manual": True,
    "ssid": True,
    "sta_ip_status": True,
    "standby_dns_manual": True,
    "static_wan_ip_address": True,
    "static_wan_status": True,
    "station_mac": True,
    "sts_received_flag": True,
    "wifi_on_off_state": True,
}

DISABLED_SENSORS_MC888 = {
    "concat_sms_received": True,
    "concat_sms_total": True,
    "content": True,
    "cr_version": True,
    "date": True,
    "id": True,
    "is_mandatory": True,
    "is_night_mode": True,
    "lte_ca_scell_arfcn": True,
    "lte_earfcn_lock": True,
    "lte_pci_lock": True,
    "sms_nv_draftbox_total": True,
    "sms_sim_total": True,
    "sms_class": True,
    "sms_dev_unread_num": True,
    "sms_sim_rev_total": True,
    "sms_sim_send_total": True,
    "sms_sim_unread_num": True,
    "sms_nv_received_total":True,
    "sms_received_flag":True,
    "tag": True,
}

DISABLED_SENSORS_MC801A = {
    "concat_sms_received": True,
    "concat_sms_total": True,
    "content": True,
    "cr_version": True,
    "date": True,
    "id": True,
    "is_mandatory": True,
    "is_night_mode": True,
    "lte_ca_scell_arfcn": True,
    "lte_earfcn_lock": True,
    "lte_pci_lock": True,
    "sms_nv_draftbox_total": True,
    "sms_sim_total": True,
    "sms_class": True,
    "sms_dev_unread_num": True,
    "sms_sim_rev_total": True,
    "sms_sim_send_total": True,
    "sms_sim_unread_num": True,
    "sms_nv_received_total":True,
    "sms_received_flag":True,
    "tag": True,
}

DISABLED_SENSORS_G5_ULTRA = DISABLED_SENSORS_MC801A.copy()
for realtime_key in [
    "flux_realtime_tx_bytes",
    "flux_realtime_rx_bytes",
    "flux_realtime_time",
    "flux_realtime_tx_thrpt",
    "flux_realtime_rx_thrpt",
]:
    DISABLED_SENSORS_G5_ULTRA[realtime_key] = False
for sms_key in [
    "sms_nv_total",
    "sms_nv_received_total",
    "sms_nv_sent_total",
    "sms_nv_draftbox_total",
    "sms_sim_total",
    "sms_sim_received_total",
    "sms_sim_sent_total",
    "sms_sim_draftbox_total",
    "sms_capacity_left",
    "sms_sim_unread_num",
    "sms_dev_unread_num",
]:
    DISABLED_SENSORS_G5_ULTRA[sms_key] = False

FLUX_KEYS = {
    "flux_realtime_tx_bytes",
    "flux_realtime_rx_bytes",
    "flux_realtime_time",
    "flux_realtime_tx_thrpt",
    "flux_realtime_rx_thrpt",
    "flux_realtime_tx_packets",
    "flux_realtime_rx_packets",
    "flux_realtime_tx_drop_packets",
    "flux_realtime_rx_drop_packets",
    "flux_realtime_tx_error_packets",
    "flux_realtime_rx_error_packets",
    "flux_realtime_max_tx_thrpt",
    "flux_realtime_max_rx_thrpt",
    "flux_monthly_tx_bytes",
    "flux_monthly_rx_bytes",
    "flux_monthly_time",
    "flux_monthly_tx_packets",
    "flux_monthly_rx_packets",
    "flux_monthly_tx_drop_packets",
    "flux_monthly_rx_drop_packets",
    "flux_monthly_tx_error_packets",
    "flux_monthly_rx_error_packets",
    "flux_data_volume_limit_size",
    "flux_data_volume_alert_percent",
    "flux_data_volume_limit_unit",
    "date_month",
    "flux_total_usage",
    "flux_total_time",
    "flux_total_tx_bytes",
    "flux_total_rx_bytes",
    "flux_total_tx_packets",
    "flux_total_rx_packets",
    "flux_total_tx_drop_packets",
    "flux_total_rx_drop_packets",
    "flux_total_tx_error_packets",
    "flux_total_rx_error_packets",
    "flux_data_volume_limit_enable",
    "flux_data_volume_limit_type",
    "flux_data_volume_overflow",
    "flux_data_volume_auto_clear_enable",
    "flux_data_volume_clearday",
}

SENSOR_NAMES.update({
    "flux_realtime_tx_bytes": "FLUX Realtime TX",
    "flux_realtime_rx_bytes": "FLUX Realtime RX",
    "flux_realtime_time": "FLUX Realtime Time",
    "flux_realtime_tx_thrpt": "FLUX Realtime TX Speed",
    "flux_realtime_rx_thrpt": "FLUX Realtime RX Speed",
    "flux_monthly_tx_bytes": "FLUX Monthly TX",
    "flux_monthly_rx_bytes": "FLUX Monthly RX",
    "flux_monthly_time": "FLUX Monthly Time",
    "flux_data_volume_limit_size": "FLUX Data Plan Limit",
    "flux_data_volume_alert_percent": "FLUX Alert Threshold",
    "flux_data_volume_limit_unit": "FLUX Limit Unit",
    "date_month": "FLUX Current Billing Month",
    "flux_total_usage": "FLUX Monthly Usage",
})

SENSOR_NAMES.update({
    "flux_monthly_tx_packets": "FLUX Monthly TX Packets",
    "flux_monthly_rx_packets": "FLUX Monthly RX Packets",
    "flux_monthly_tx_drop_packets": "FLUX Monthly TX Drops",
    "flux_monthly_rx_drop_packets": "FLUX Monthly RX Drops",
    "flux_monthly_tx_error_packets": "FLUX Monthly TX Errors",
    "flux_monthly_rx_error_packets": "FLUX Monthly RX Errors",
    "flux_realtime_tx_packets": "FLUX Realtime TX Packets",
    "flux_realtime_rx_packets": "FLUX Realtime RX Packets",
    "flux_realtime_tx_drop_packets": "FLUX Realtime TX Drops",
    "flux_realtime_rx_drop_packets": "FLUX Realtime RX Drops",
    "flux_realtime_tx_error_packets": "FLUX Realtime TX Errors",
    "flux_realtime_rx_error_packets": "FLUX Realtime RX Errors",
    "flux_realtime_max_tx_thrpt": "FLUX Peak TX Speed",
    "flux_realtime_max_rx_thrpt": "FLUX Peak RX Speed",
    "flux_total_time": "FLUX Total Connected Time",
    "flux_total_tx_bytes": "FLUX Total TX",
    "flux_total_rx_bytes": "FLUX Total RX",
    "flux_total_tx_packets": "FLUX Total TX Packets",
    "flux_total_rx_packets": "FLUX Total RX Packets",
    "flux_total_tx_drop_packets": "FLUX Total TX Drops",
    "flux_total_rx_drop_packets": "FLUX Total RX Drops",
    "flux_total_tx_error_packets": "FLUX Total TX Errors",
    "flux_total_rx_error_packets": "FLUX Total RX Errors",
    "flux_data_volume_limit_enable": "FLUX Data Plan Enabled",
    "flux_data_volume_limit_type": "FLUX Data Plan Type",
    "flux_data_volume_overflow": "FLUX Data Plan Overflow",
    "flux_data_volume_auto_clear_enable": "FLUX Auto Clear Enabled",
    "flux_data_volume_clearday": "FLUX Auto Clear Day",
    "current_wan_status": "Current WAN Status",
    "mwan_wanlan1_link_state": "WAN/LAN1 Link State",
    "mwan_wanlan1_link_mode": "WAN/LAN1 Link Mode",
    "mwan_wanlan1_status": "WAN/LAN1 Status",
    "mwan_wanlan1_wan_ipaddr": "WAN/LAN1 IP Address",
    "mwan_wanlan1_wan_netmask": "WAN/LAN1 Netmask",
    "mwan_wanlan1_wan_gateway": "WAN/LAN1 Gateway",
    "mwan_wanlan1_prefer_dns_auto": "WAN/LAN1 Preferred DNS",
    "mwan_wanlan1_standby_dns_auto": "WAN/LAN1 Standby DNS",
    "mwan_wanlan1_ipv6_wan_ipaddr": "WAN/LAN1 IPv6 Address",
    "mwan_wanlan1_ipv6_wan_gateway": "WAN/LAN1 IPv6 Gateway",
    "mwan_wanlan1_ipv6_prefer_dns_auto": "WAN/LAN1 IPv6 Preferred DNS",
    "mwan_wanlan1_ipv6_standby_dns_auto": "WAN/LAN1 IPv6 Standby DNS",
    "mwan_wanlan1_linkup_speed": "WAN/LAN1 Link-Up Speed",
    "mwan_wanlan1_linkdown_speed": "WAN/LAN1 Link-Down Speed",
    "tar_keylog_result": "Trace Capture Result",
    "tar_keylog_name": "Trace Capture Name",
    "tcpdump_running": "TCPDump Running",
    "modem_log_running": "Modem Log Capture",
    "sim_states": "SIM State",
    "sim_iccid": "SIM ICCID",
    "pinnumber": "PIN Retries Remaining",
    "puknumber": "PUK Retries Remaining",
    "pin_save_flag": "PIN Save Flag",
    "msisdn": "MSISDN",
    "wlan_mac_address": "WiFi MAC Address",
    "Operator": "Operator",
    "switch_card_status": "SIM Switch Status",
    "current_sim_slot": "Current SIM Slot",
    "night_mode_switch": "Night Mode Switch",
    "night_mode_starttime": "Night Mode Start",
    "night_mode_endtime": "Night Mode End",
    "night_mode_is_nightmode": "Night Mode Active",
    "wifi_status_dfs_status": "Mesh DFS Status",
    "wifi_status_load_status": "WiFi Load Status",
    "wifi_status_mesh_deployed": "Mesh Deployed",
    "wifi_status_mesh_deploying_status": "Mesh Deploying Status",
    "wifi_status_mesh_set_status": "Mesh Settings Status",
    "wifi_status_wifi_onoff": "WiFi Switch",
    "wifi_status_lbd_enable": "WiFi Load Balancing",
    "wifi_status_mlo_enable": "WiFi MLO Enabled",
    "wifi_status_main2g_ssid": "WiFi 2.4G SSID",
    "wifi_status_main2g_authmode": "WiFi 2.4G Auth Mode",
    "wifi_status_main5g_ssid": "WiFi 5G SSID",
    "wifi_status_main5g_authmode": "WiFi 5G Auth Mode",
    "wifi_status_main6g_ssid": "WiFi 6G SSID",
    "wifi_status_main6g_authmode": "WiFi 6G Auth Mode",
    "wifi_status_wifi_start_mode": "WiFi Start Mode",
    "wifi_status_radio2": "2.4G Radio Identifier",
    "wifi_status_radio5": "5G Radio Identifier",
    "wifi_status_radio6": "6G Radio Identifier",
    "user_count_access_total_num": "Total Connected Devices",
    "user_count_lan_num": "LAN Device Count",
    "user_count_wireless_num": "Wireless Device Count",
    "user_count_offline_num": "Offline Device Count",
    "user_count_guest_num_24g": "Guest 2.4G Device Count",
    "user_count_guest_num_5g": "Guest 5G Device Count",
    "user_count_guest_num_6g": "Guest 6G Device Count",
})

# Mapping of icons for each flux key
FLUX_ICON_MAP = {
    "flux_realtime_tx_bytes": "mdi:upload",
    "flux_realtime_rx_bytes": "mdi:download",
    "flux_realtime_time": "mdi:clock-time-four-outline",
    "flux_realtime_tx_thrpt": "mdi:upload-network",
    "flux_realtime_rx_thrpt": "mdi:download-network",
    "flux_realtime_tx_packets": "mdi:upload",
    "flux_realtime_rx_packets": "mdi:download",
    "flux_realtime_tx_drop_packets": "mdi:upload-off",
    "flux_realtime_rx_drop_packets": "mdi:download-off",
    "flux_realtime_tx_error_packets": "mdi:alert-octagon",
    "flux_realtime_rx_error_packets": "mdi:alert-octagon-outline",
    "flux_realtime_max_tx_thrpt": "mdi:speedometer",
    "flux_realtime_max_rx_thrpt": "mdi:speedometer",
    "flux_monthly_tx_bytes": "mdi:upload",
    "flux_monthly_rx_bytes": "mdi:download",
    "flux_monthly_time": "mdi:clock-time-four-outline",
    "flux_monthly_tx_packets": "mdi:upload",
    "flux_monthly_rx_packets": "mdi:download",
    "flux_monthly_tx_drop_packets": "mdi:upload-off",
    "flux_monthly_rx_drop_packets": "mdi:download-off",
    "flux_monthly_tx_error_packets": "mdi:alert-octagon",
    "flux_monthly_rx_error_packets": "mdi:alert-octagon-outline",
    "flux_data_volume_limit_size": "mdi:database",
    "flux_data_volume_alert_percent": "mdi:alert",
    "flux_data_volume_limit_unit": "mdi:weight",
    "flux_data_volume_limit_enable": "mdi:toggle-switch",
    "flux_data_volume_limit_type": "mdi:format-list-bulleted",
    "flux_data_volume_overflow": "mdi:water-alert",
    "flux_data_volume_auto_clear_enable": "mdi:autorenew",
    "flux_data_volume_clearday": "mdi:calendar-check",
    "date_month": "mdi:calendar",
    "flux_total_usage": "mdi:chart-bar",
    "flux_total_time": "mdi:clock-time-eight-outline",
    "flux_total_tx_bytes": "mdi:upload",
    "flux_total_rx_bytes": "mdi:download",
    "flux_total_tx_packets": "mdi:upload",
    "flux_total_rx_packets": "mdi:download",
    "flux_total_tx_drop_packets": "mdi:upload-off",
    "flux_total_rx_drop_packets": "mdi:download-off",
    "flux_total_tx_error_packets": "mdi:alert-octagon",
    "flux_total_rx_error_packets": "mdi:alert-octagon-outline",
}

# G5 Ultra beta: DDNS is read-only (no way to safely write the password back
# via a switch), so it's exposed as plain sensors via the generic sensor loop
# in sensor.py rather than a dedicated switch entity.
SENSOR_NAMES.update({
    "ddns_enabled": "DDNS Enabled",
    "ddns_service": "DDNS Service",
    "ddns_domain": "DDNS Domain",
    "ddns_status_text": "DDNS Status",
})

# G5 Ultra: friendly names for fields that were falling back to their raw
# ubus/UCI key names in the sensor list.
SENSOR_NAMES.update({
    "boot_version": "Boot Version",
    "cid": "Connection ID",
    "connect_fail_count": "Connection Fail Count",
    "connect_mode": "Connect Mode",
    "connect_status": "Connection Status",
    "devui_get_sim_info": "SIM Info (Raw)",
    "domain_stat": "Domain Status",
    "enable": "WWAN Enabled",
    "error": "Error",
    "gw_band_lock": "GW Band Lock",
    "integrate_version": "Integrate Version",
    "ipv4_address": "IPv4 WAN Address",
    "ipv4_dev_name": "IPv4 Device Name",
    "ipv4_dns_prefer": "IPv4 Preferred DNS",
    "ipv4_dns_standby": "IPv4 Standby DNS",
    "ipv4_gateway": "IPv4 Gateway",
    "ipv4_netmask": "IPv4 Netmask",
    "ipv6_address": "IPv6 WAN Address",
    "ipv6_dev_name": "IPv6 Device Name",
    "ipv6_dns_prefer": "IPv6 Preferred DNS",
    "ipv6_dns_standby": "IPv6 Standby DNS",
    "ipv6_gateway": "IPv6 Gateway",
    "lac_code": "LAC Code",
    "lock_lte_cell": "LTE Cell Lock",
    "lock_nr_cell": "5G NR Cell Lock",
    "lte_band_lock": "LTE Band Lock",
    "lte_neighbor_cell": "LTE Neighbor Cells",
    "lteca": "LTE Carrier Aggregation",
    "lteca_state": "LTE CA State",
    "ltecasig": "LTE CA Signal",
    "manufacturer": "Manufacturer",
    "model_name": "Model Name",
    "net_select": "Network Selection Mode",
    "net_select_mode": "Network Selection Sub-Mode",
    "nitz_sync_flag": "NITZ Sync Enabled",
    "nitz_timezone": "NITZ Timezone",
    "nr5g_bandwidth": "5G NR Bandwidth",
    "nr5g_nrdc_band_lock": "5G NR-DC Band Lock",
    "nr5g_rsrp": "5G NR RSRP",
    "nr5g_rsrq": "5G NR RSRQ",
    "nr5g_rssi": "5G NR RSSI",
    "nr5g_snr": "5G NR SNR",
    "nrca": "5G NR Carrier Aggregation",
    "nr_neighbor_cell": "5G NR Neighbor Cells",
    "pin_manage_at_wait": "PIN Management Pending",
    "pin_manage_result": "PIN Management Result",
    "pin_puk_at_wait": "PUK Management Pending",
    "roam_enable": "Roaming Enabled",
    "roll_connect_status": "Rollback Connect Status",
    "sim_card_number": "SIM Card Number",
    "sim_gid1": "SIM GID1",
    "sim_gid1_string": "SIM GID1 String",
    "wa_module_version": "WA Module Version",
    "wireless_name": "Wireless Module Name",
    "wan_ipv6_address": "WAN IPv6 Address",
})
