name: Increment Version and Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read current version from manifest.json
      id: read_version
      run: |
        VERSION=$(jq -r '.version' custom_components/zte_router/manifest.json)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "Current version: ${VERSION}"

    - name: Increment version
      id: increment_version
      run: |
        IFS='.' read -r major minor patch <<< "${{ env.VERSION }}"
        NEW_VERSION="${major}.${minor}.$((patch + 1))"
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
        jq --arg new_version "$NEW_VERSION" '.version = $new_version' custom_components/zte_router/manifest.json > temp.json && mv temp.json custom_components/zte_router/manifest.json
        echo "New version: ${NEW_VERSION}"

    - name: Display updated version
      run: echo "New version is ${{ env.NEW_VERSION }}"

    - name: Zip files
      run: zip -r zte_router.zip custom_components/zte_router

    - name: Get last commit message
      id: last_commit
      run: |
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
        echo "LAST_COMMIT_MESSAGE=${LAST_COMMIT_MESSAGE}" >> $GITHUB_ENV
        echo "Last commit message: ${LAST_COMMIT_MESSAGE}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: ZTE_MC_HA_CI_v${{ env.NEW_VERSION }}
        body: |
          Changes in this release:
          - ${{ env.LAST_COMMIT_MESSAGE }}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zte_router.zip
        asset_name: zte_router.zip
        asset_content_type: application/zip
