name: Create Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Read current version from manifest.json
      id: read_version
      run: |
        VERSION=$(jq -r '.version' custom_components/zte_router/manifest.json)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "Current version: ${VERSION}"

    - name: Display current version
      run: echo "VERSION=${{ env.VERSION }}"

    - name: Zip files
      run: zip -r zte_router.zip custom_components/zte_router

    - name: Get last commit message
      id: last_commit
      run: |
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
        echo "LAST_COMMIT_MESSAGE=${LAST_COMMIT_MESSAGE}" >> $GITHUB_ENV
        echo "Last commit message: ${LAST_COMMIT_MESSAGE}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1  # v1 uses Node16/Node20 automatically
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: ZTE_MC_HA_CI_v${{ env.VERSION }}
        body: |
          Changes in this release:
          - ${{ env.LAST_COMMIT_MESSAGE }}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1  # v1 uses Node16/Node20 automatically
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zte_router.zip
        asset_name: zte_router.zip
        asset_content_type: application/zip
